### ISSUE TITLE
Unable to Upload Images to Cloudinary - Unauthorized (401) Error

### ISSUE THREAD

**Issue by pybotlad** [leanhduy/threads-clone#20]
**Environment**: 
- Application: Production
- Client: https://thread-clone-lad.netlify.app/
- GraphQL Server:  https://threads-clone-backend-qlla.onrender.com
- Database: PostgresSQL on [Supabase](https://supabase.com/dashboard/project/mogrfegujdlijfgopmob)
- Browser: Chrome 125

**Description**: When attempting to upload an image to Cloudinary from the local computer while creating a new post, an Unauthorized (401) status code is returned. This issue prevents the post from being created successfully. 

**Expected**: After filling in the body and selecting images from the local computer, clicking the "Post" button should create a new post without any issues. The images should be uploaded to Cloudinary and attached to the post.

**Actual**
- The post cannot be created. An error message indicating an Unauthorized (401) status code is displayed in the browser's console.
![image](https://github.com/leanhduy/threads-clone/assets/120729261/ec423cbe-6ab6-485a-89d5-c21a7d235f9d)
- Detail of the error:

> // 20240612163408
> // https://api.cloudinary.com/v1_1/undefined/image/upload
> 
> {
>   "error": {
>     "message": "cloud_name is disabled"
>   }
> }

**Steps to reproduce**

1. Click on the "Create New Task" icon or the "Quick Create" button.
2. Draft the post's body.
3. Select images from the local computer to upload.
4. Click the "Post" button.
5. Observe the error message in the browser console.
![image](https://github.com/leanhduy/threads-clone/assets/120729261/fd718f03-6967-4e7f-b236-550b447d3689)

**Comment by leanhduy** [comment]
There is no change in code for this issue.
**Root cause**: There is no environment variables set up on the client server on Netlify. 
**Fix**: Adding necessary environment variables to Netlify and redeploying the site
