### ISSUE TITLE
Wrong sorting order for the list of posts on Home page

### ISSUE THREAD

**Issue by pybotlad** [leanhduy/threads-clone#21]
**Description**: On the home page, the list of posts is being sorted by id in the ascending order. This is not correct. The list of post should be sorted in the descending order.

Expected: The list of posts is sorted by id / created date, in descending order
Actual: The list of posts is being sorted by id in ascending order.

**Comment by leanhduy** [comment]
The fix is completed and tested.
The changes is included in [PR#24](https://github.com/leanhduy/threads-clone/pull/24)
