### ISSUE TITLE
Incorrectly fetched list of account in the Search page.

### ISSUE THREAD

**Issue by pybotlad** [leanhduy/threads-clone#22]
**Description**
When navigating to the Search page from any other pages, the list of user is currently fetched in correctly. Only last 5 users are visible.

**Expected**: All users in the database should be fetched and listed in the infinite scroll manner
**Actual**: Only last 5 users is visible.
![image](https://github.com/leanhduy/threads-clone/assets/120729261/1faa76b2-a5dd-4843-98de-62a074bb28bf)

**Comment by leanhduy** [comment]
Fixed in the [PR#25](https://github.com/leanhduy/threads-clone/pull/25)
