### ISSUE TITLE
Null user id causing homepage not loaded

### ISSUE THREAD

**Issue by pybotlad** [leanhduy/threads-clone#31]
**Environment**
- Production

**Screenshot(s)**
<img width="1553" alt="Screenshot 2024-06-22 at 18 49 24" src="https://github.com/leanhduy/threads-clone/assets/120729261/4deee293-497f-4f0d-87c1-3bd796dd4800">

**Comment by pybotlad** [comment]
Possible cause could be the `user Id` is set and initialized incorrectly in the context. 
Try this approach and test again if it solved the problem.
1. Ensure User Context is Set Properly: Make sure the UserContext is properly set and updated when the user logs in. If you have an authentication mechanism, ensure it correctly updates the UserContext.
2. Add a Fallback for userId: If the userId is null, handle this case to prevent the query from running with null as a variable.
3. Ensure User Context is Available on Page Load: Sometimes, the context might not be available immediately on page load due to asynchronous operations. You can add a loading state to handle this.

For lazy person 😂

import React, { useContext, useEffect, useRef, useState } from 'react'
import styled from '@emotion/styled'
import { useQuery } from '@apollo/client'
import { Layout, NewPostDialog, QueryResult } from '../components'
import { Post } from '../container'
import { colors, ToggleIcon } from '../styles'
import { Button } from '@mui/material'
import { Link } from 'react-router-dom'
import { FEED_FOR_YOU, GET_USER_BY_ID, userProfilePlaceHolder } from '../utils'
import { UserContext } from '../context'

const Home = () => {
    // * Top-level states / variables
    // ? Indicates the number of posts to skip for the next query
    const [skip, setSkip] = useState(0)
    // ? Stores the list of posts fetched in the current query
    const [posts, setPosts] = useState([])
    // ? Ref to the element at the end of the post list for infinite scroll
    const ref = useRef()

    const [isCreatingNewPost, setIsCreatingNewPost] = useState(false)
    const [isUserLoading, setIsUserLoading] = useState(true)  // State to track user loading

    // * Client-side GraphQL queries
    // ? Get the data of current logged in user in the context
    const { userId } = useContext(UserContext)

    // ? Fetch the current logged-in user
    const {
        data: loggedInUser,
        loading: loadingUser,
        error: errorUser,
    } = useQuery(GET_USER_BY_ID, {
        variables: { id: userId ? parseInt(userId) : 0 },
        skip: !userId, // Skip the query if no userId
        onCompleted: () => setIsUserLoading(false),
        onError: () => setIsUserLoading(false)
    })

    // ? Fetch the posts gradually
    const { data, refetch } = useQuery(FEED_FOR_YOU, {
        variables: { skip: skip },
    })

    // * HANDLERS
    const handleOpenNewPostDialog = () => {
        setIsCreatingNewPost(true)
    }

    const handleCloseNewPostDialog = () => {
        setIsCreatingNewPost(false)
    }

    // * SIDE-EFFECTS

    // ? Keep track of the fetched data of the GraphQL query and update the `posts` states
    useEffect(() => {
        if (data) {
            if (posts.length === 0) {
                setPosts(data.feedForYou.posts)
            } else {
                setPosts([...posts, ...data.feedForYou.posts])
            }
        }
    }, [data])

    // ? Leverage the Intersection Observer API for fetching data using infinite scroll
    useEffect(() => {
        const observer = new IntersectionObserver((entries) => {
            const entry = entries[0]
            if (entry.isIntersecting) {
                if (data) {
                    setSkip(posts.length)
                }
            }
        })

        if (ref.current) {
            observer.observe(ref.current)
        }

        return () => {
            if (ref.current) {
                observer.unobserve(ref.current)
            }
        }
    }, [posts])

    // Render loading state until userId is determined and user query is completed
    if (isUserLoading) {
        return (
            <Layout grid>
                <CircularProgress />
            </Layout>
        )
    }

    return (
        <Layout grid>
            {/* Only display <NewThread/> component if user is logged in */}
            {userId && (
                <QueryResult
                    loading={loadingUser}
                    data={loggedInUser}
                    error={errorUser}
                >
                    <NewThread>
                        <LinkContainer
                            to={`/profile/${loggedInUser?.userById?.username}`}
                        >
                            <PostAvatarImage
                                src={
                                    loggedInUser?.userById?.profileImage?.url ||
                                    userProfilePlaceHolder
                                }
                            />
                        </LinkContainer>
                        <TextButton onClick={handleOpenNewPostDialog}>
                            Start a thread...
                        </TextButton>
                        <StyledButton
                            variant="outlined"
                            onClick={handleOpenNewPostDialog}
                        >
                            Post
                        </StyledButton>
                    </NewThread>
                </QueryResult>
            )}
            {/* List of Posts */}
            {posts.map((post) => (
                <Post key={post.id} post={post} />
            ))}
            {/* UI Element to trigger the infinite scroll fetching*/}
            <p ref={ref}></p>
            {/* Feed mode toggle button */}
            <FeedModeToggleButton
                disableRipple
                variant="outlined"
                startIcon={<ToggleIcon />}
            >
                Following
            </FeedModeToggleButton>
            <NewPostDialog
                isCreateNewPost={isCreatingNewPost}
                closeNewPostDialog={handleCloseNewPostDialog}
                refetchPosts={refetch}
            />
        </Layout>
    )
}

export default Home

//#region Styled-components
const NewThread = styled.div({
    border: `1px solid ${colors.grey.lighter}`,
    borderBottom: 'none',
    borderRadius: '30px 30px 0 0',
    backgroundColor: colors.white,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: '.5rem',
    padding: '1.5rem 2rem',
    width: '100%',
})

const PostAvatarImage = styled.img({
    borderRadius: '50%',
    objectFit: 'cover',
    width: 40,
    height: 40,
    ':hover': {
        cursor: 'pointer',
    },
})

const TextButton = styled(Button)({
    color: colors.grey.base,
    display: 'flex',
    flexGrow: 1,
    justifyContent: 'flex-start',
    textTransform: 'none',
    textAlign: 'right',
    ':hover': {
        cursor: 'text',
    },
})

const StyledButton = styled(Button)({
    '&.MuiButton-outlined': {
        borderColor: colors.silver.darker,
        borderRadius: '10px',
        color: colors.black.base,
        fontWeight: 600,
        textTransform: 'none',
    },
})

const FeedModeToggleButton = styled(Button)({
    position: 'fixed',
    bottom: '1rem',
    left: '1rem',
    '&.MuiButton-outlined': {
        borderColor: colors.silver.darker,
        borderRadius: '10px',
        color: colors.black.base,
        fontWeight: 600,
        textTransform: 'none',
    },
})

const LinkContainer = styled(Link)({
    textDecoration: 'none',
})
//#endregion Styled-components

**Comment by leanhduy** [comment]
Close the issue now since it cannot be reproduced, after clearing the cookies and cache of browser. May be clearing the cache and browser clear the stale state that intefered and causing the problem. Might need to look at the next build to see if the issue happen again. When it does, this issue will be reopened.
